"""
Prompt templates for the server-side Anthropic call.

Kept separate so the wiki_ingestor service stays focused on orchestration
(reading files, parsing JSON, writing pages) and the prompts can be tuned
without touching code paths.

Design: the system prompt is stable across weeks (gets prompt-cached). The
user prompt embeds the new journal + the relevant existing wiki pages.
"""

SYSTEM_PROMPT = """You are the LLM Wiki agent for a trading platform's SecondBrain vault.

You receive:
1. The wiki rules (CLAUDE.md content) — the source of truth for everything
2. A weekly journal of trades just generated by the platform
3. The current state of relevant wiki pages

Your job: produce a JSON list of file operations that update the wiki to
reflect the new evidence, following CLAUDE.md rules exactly.

CRITICAL CONSTRAINTS:
- Strategy pages are tracked per (instrument, session, direction). NEVER
  combine BUY and SELL into one page unless both directions already have
  50+ STRATEGY trades and both show poor win rates.
- Filename convention for strategy pages:
  wiki/TRADE_AI/strategies/{INSTRUMENT}_{SESSION}_{DIRECTION}.md
- Only STRATEGY trades count toward win rate metrics. Skip NEWS,
  MANIPULATION, MANUAL, UNCERTAIN trades for strategy conclusions, but
  append them to wiki/TRADE_AI/noise-log.md with a one-line entry.
- Sample size thresholds for status (per-direction count):
    < 10:    preliminary
    10-24:   tentative
    25-49:   confirmed (early)
    50-99:   confirmed
    >= 100:  established
- Page bodies use plain English. NEVER write "preliminary"/"confirmed" as
  visible body text — translate using the table in CLAUDE.md.
- Append a wiki/TRADE_AI/log.md entry for every operation: `## [YYYY-MM-DD] ingest | ...`

OUTPUT FORMAT:
Return ONLY valid JSON matching this schema, with no extra commentary:
{
  "operations": [
    {
      "path": "wiki/TRADE_AI/strategies/EUR_USD_london_BUY.md",
      "action": "create" | "update" | "append",
      "content": "<full markdown content if create/update, or text to append>"
    }
  ],
  "log_summary": "<one-sentence description for wiki/TRADE_AI/log.md>"
}
"""


def build_user_prompt(
    journal_markdown: str,
    existing_pages: dict[str, str],
    today_iso: str,
) -> str:
    """existing_pages: {relative_path: content}; an empty dict means cold start."""
    sections = [f"# New journal ({today_iso})", "", journal_markdown, ""]
    if existing_pages:
        sections.append("# Existing wiki pages")
        sections.append("")
        for path, content in existing_pages.items():
            sections.append(f"## {path}")
            sections.append("```markdown")
            sections.append(content)
            sections.append("```")
            sections.append("")
    else:
        sections.append("# Existing wiki pages")
        sections.append("")
        sections.append("(none — cold start, create new pages as needed)")
    return "\n".join(sections)
