-- ══════════════════════════════════════════════════════════════════════
-- Slim seed loader — generated by backend/scripts/export_slim_seed.py
-- Generated: 2026-09-01T17:53:26.361651+00:00
--
-- PREREQUISITE: run `alembic upgrade head` on the target FIRST. This file
-- carries DATA ONLY — no DDL. Loading into a database without the schema
-- fails on the first \copy.
--
-- Run from INSIDE the directory holding the .csv files (\copy resolves
-- paths client-side, relative to psql's working directory):
--
--     psql -v ON_ERROR_STOP=1 -h <host> -U <user> -d <db> -f load.sql
--
-- ON_ERROR_STOP=1 matters: without it psql reports failures and keeps
-- going, leaving a half-loaded database that looks like it worked.
--
-- Target tables must be EMPTY. There is no TRUNCATE here on purpose —
-- a seed loader that silently wipes tables is one fat-finger away from
-- destroying a live corpus. A primary-key collision aborting the run is
-- the safe failure.
-- ══════════════════════════════════════════════════════════════════════

BEGIN;

-- instruments: ALL rows — the universe, is_active flags and pip_size everything else FKs to.
\copy instruments (id, symbol, display_name, pip_size, pip_location, asset_class, broker_id, is_active) FROM 'instruments.csv' WITH (FORMAT csv, HEADER true)

-- macro_data: ALL rows — bitemporal FRED vintages read point-in-time by feature_builder.
\copy macro_data (id, series, ref_period, release_time, value) FROM 'macro_data.csv' WITH (FORMAT csv, HEADER true)

-- news_calendar_events: ALL rows — the forward calendar spine, including future-dated events.
\copy news_calendar_events (id, event_key, timestamp, currency, impact, title, is_tier1, all_day, source, fetched_at) FROM 'news_calendar_events.csv' WITH (FORMAT csv, HEADER true)

-- candles: price_type='M' only, newest 1000 H4, 200 D bars per instrument. NO M1 ROWS — the hourly trailing-window job rebuilds the live M1 series from empty (this is the ~99.8% size win).
\copy candles (id, instrument_id, granularity, price_type, timestamp, open, high, low, close, volume) FROM 'candles.csv' WITH (FORMAT csv, HEADER true)

-- indicators: newest 1000 H4, 60 D rows per instrument — recomputable, shipped so the first live candle-close job can fire immediately.
\copy indicators (id, instrument_id, granularity, timestamp, atr14, rsi14, swing_high, swing_low) FROM 'indicators.csv' WITH (FORMAT csv, HEADER true)

-- trades: ALL rows — M7 backtest corpus (S1 training set) + any recorded shadow rows. ~12 MB. Omit with --no-trades for an observation-only deploy.
\copy trades (id, instrument_id, direction, entry_price, exit_price, stop_price, tp_price, units, risk_amount, expected_pip_loss, actual_pip_loss, slippage, rr_entry, rr_actual, signal_source, stage, outcome, exit_reason, ambiguous_resolution, opened_at, closed_at, signal_reasoning, confluence_score, session, stop_method, news_events, ml_probability, ml_decision, ml_model_id, auto_classification, classification_confidence, human_classification_override, final_classification) FROM 'trades.csv' WITH (FORMAT csv, HEADER true)

-- ── sequence repair ──────────────────────────────────────────────────
-- \copy writes explicit id values, which does NOT advance the identity
-- sequence. Without this block the next INSERT reuses id=1 and dies on a
-- duplicate-key error — and it dies inside a scheduled job on the server,
-- hours after the deploy looked successful.
-- coalesce(max(id), 0) + 1 with is_called=false handles an empty table.

SELECT setval(pg_get_serial_sequence('instruments', 'id'), coalesce((SELECT max(id) FROM instruments), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('macro_data', 'id'), coalesce((SELECT max(id) FROM macro_data), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('news_calendar_events', 'id'), coalesce((SELECT max(id) FROM news_calendar_events), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('candles', 'id'), coalesce((SELECT max(id) FROM candles), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('indicators', 'id'), coalesce((SELECT max(id) FROM indicators), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('trades', 'id'), coalesce((SELECT max(id) FROM trades), 0) + 1, false);

COMMIT;
