"""add price_type to candles (Pre-M7 Step 1.6 — candle standardization)

Adds price_type (M|B|A) to candles, backfills existing rows to 'M', and widens
the unique constraint from (instrument_id, granularity, timestamp) to also include
price_type — so Bid and Ask candles can coexist with Mid at the same timestamp.

Revision ID: 20260603_candles_price_type
Revises: 20260602_baseline_schema
Create Date: 2026-06-03
"""
from alembic import op
import sqlalchemy as sa

revision = "20260603_candles_price_type"
down_revision = "20260602_baseline_schema"
branch_labels = None
depends_on = None

_NEW_UQ = "uq_candles_inst_gran_ts_price"


def upgrade() -> None:
    # 1. Add column with a server default so all existing (Mid) rows backfill to 'M'.
    op.add_column(
        "candles",
        sa.Column("price_type", sa.String(), nullable=False, server_default="M"),
    )
    # 2. Drop the server default — the model/app supplies the value going forward.
    op.alter_column("candles", "price_type", server_default=None)

    # 3. Drop the existing 3-column unique constraint (name is auto-generated by
    #    Postgres, so discover it dynamically rather than hardcode) and replace it
    #    with the 4-column constraint that includes price_type.
    conn = op.get_bind()
    existing = conn.execute(
        sa.text(
            "SELECT conname FROM pg_constraint "
            "WHERE conrelid = 'candles'::regclass AND contype = 'u'"
        )
    ).fetchall()
    for (name,) in existing:
        op.drop_constraint(name, "candles", type_="unique")

    op.create_unique_constraint(
        _NEW_UQ,
        "candles",
        ["instrument_id", "granularity", "timestamp", "price_type"],
    )


def downgrade() -> None:
    # Note: only reversible while the table holds Mid-only data. Once Bid/Ask rows
    # exist, the 3-column constraint below would be violated by duplicate
    # (instrument_id, granularity, timestamp) across price types.
    op.drop_constraint(_NEW_UQ, "candles", type_="unique")
    op.create_unique_constraint(
        "candles_instrument_id_granularity_timestamp_key",
        "candles",
        ["instrument_id", "granularity", "timestamp"],
    )
    op.drop_column("candles", "price_type")
