"""add macro_data

Revision ID: 20260604_add_macro_data
Revises: 20260603_candles_price_type
Create Date: 2026-06-04 06:39:44.179081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260604_add_macro_data'
down_revision: Union[str, None] = '20260603_candles_price_type'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(), nullable=False),
    sa.Column('ref_period', sa.String(), nullable=False),
    sa.Column('release_time', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series', 'ref_period', 'release_time', name='uq_macro_series_period_vintage')
    )
    op.create_index(op.f('ix_macro_data_release_time'), 'macro_data', ['release_time'], unique=False)
    op.create_index(op.f('ix_macro_data_series'), 'macro_data', ['series'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_macro_data_series'), table_name='macro_data')
    op.drop_index(op.f('ix_macro_data_release_time'), table_name='macro_data')
    op.drop_table('macro_data')
    # ### end Alembic commands ###
