"""add news_calendar_events

Revision ID: 20260605_news_calendar_events
Revises: 20260604_add_macro_data
Create Date: 2026-06-04 18:02:05.212883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260605_news_calendar_events'
down_revision: Union[str, None] = '20260604_add_macro_data'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('impact', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_tier1', sa.Boolean(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_index(op.f('ix_news_calendar_events_currency'), 'news_calendar_events', ['currency'], unique=False)
    op.create_index(op.f('ix_news_calendar_events_source'), 'news_calendar_events', ['source'], unique=False)
    op.create_index(op.f('ix_news_calendar_events_timestamp'), 'news_calendar_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_calendar_events_timestamp'), table_name='news_calendar_events')
    op.drop_index(op.f('ix_news_calendar_events_source'), table_name='news_calendar_events')
    op.drop_index(op.f('ix_news_calendar_events_currency'), table_name='news_calendar_events')
    op.drop_table('news_calendar_events')
    # ### end Alembic commands ###
