"""baseline schema

Revision ID: 20260602_baseline_schema
Revises:
Create Date: 2026-06-02 03:39:10.336784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260602_baseline_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('paused_reason', sa.String(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('last_resumed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equity_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('unrealised_pnl', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equity_points_timestamp'), 'equity_points', ['timestamp'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('pip_size', sa.Float(), nullable=False),
    sa.Column('pip_location', sa.Integer(), nullable=False),
    sa.Column('asset_class', sa.String(), nullable=False),
    sa.Column('broker_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=True)
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('in_sample_start', sa.DateTime(), nullable=False),
    sa.Column('in_sample_end', sa.DateTime(), nullable=False),
    sa.Column('oos_start', sa.DateTime(), nullable=False),
    sa.Column('oos_end', sa.DateTime(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('avg_rr', sa.Float(), nullable=False),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('sharpe', sa.Float(), nullable=False),
    sa.Column('expectancy', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_instrument_id'), 'backtest_runs', ['instrument_id'], unique=False)
    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('granularity', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'granularity', 'timestamp')
    )
    op.create_index(op.f('ix_candles_instrument_id'), 'candles', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_candles_timestamp'), 'candles', ['timestamp'], unique=False)
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('granularity', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('atr14', sa.Float(), nullable=True),
    sa.Column('rsi14', sa.Float(), nullable=True),
    sa.Column('swing_high', sa.Float(), nullable=True),
    sa.Column('swing_low', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'granularity', 'timestamp')
    )
    op.create_index(op.f('ix_indicators_instrument_id'), 'indicators', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_indicators_timestamp'), 'indicators', ['timestamp'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('granularity', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('entry', sa.Float(), nullable=False),
    sa.Column('stop', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_created_at', 'signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_signals_instrument_id'), 'signals', ['instrument_id'], unique=False)
    op.create_index('ix_signals_instrument_status', 'signals', ['instrument_id', 'status'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('tp_price', sa.Float(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('risk_amount', sa.Float(), nullable=False),
    sa.Column('expected_pip_loss', sa.Float(), nullable=False),
    sa.Column('actual_pip_loss', sa.Float(), nullable=True),
    sa.Column('slippage', sa.Float(), nullable=True),
    sa.Column('rr_entry', sa.Float(), nullable=False),
    sa.Column('rr_actual', sa.Float(), nullable=True),
    sa.Column('signal_source', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('signal_reasoning', sa.JSON(), nullable=True),
    sa.Column('confluence_score', sa.Integer(), nullable=True),
    sa.Column('session', sa.String(), nullable=True),
    sa.Column('stop_method', sa.String(), nullable=True),
    sa.Column('news_events', sa.JSON(), nullable=True),
    sa.Column('auto_classification', sa.String(), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('human_classification_override', sa.String(), nullable=True),
    sa.Column('final_classification', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_auto_classification'), 'trades', ['auto_classification'], unique=False)
    op.create_index(op.f('ix_trades_final_classification'), 'trades', ['final_classification'], unique=False)
    op.create_index(op.f('ix_trades_instrument_id'), 'trades', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_trades_session'), 'trades', ['session'], unique=False)
    op.create_index(op.f('ix_trades_stage'), 'trades', ['stage'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('broker_order_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_instrument_id'), 'orders', ['instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_instrument_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_trades_stage'), table_name='trades')
    op.drop_index(op.f('ix_trades_session'), table_name='trades')
    op.drop_index(op.f('ix_trades_instrument_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_final_classification'), table_name='trades')
    op.drop_index(op.f('ix_trades_auto_classification'), table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_signals_instrument_status', table_name='signals')
    op.drop_index(op.f('ix_signals_instrument_id'), table_name='signals')
    op.drop_index('ix_signals_created_at', table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_indicators_timestamp'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_instrument_id'), table_name='indicators')
    op.drop_table('indicators')
    op.drop_index(op.f('ix_candles_timestamp'), table_name='candles')
    op.drop_index(op.f('ix_candles_instrument_id'), table_name='candles')
    op.drop_table('candles')
    op.drop_index(op.f('ix_backtest_runs_instrument_id'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_equity_points_timestamp'), table_name='equity_points')
    op.drop_table('equity_points')
    op.drop_table('bot_state')
    # ### end Alembic commands ###
